Repository neomatrix369/awesome-ai-ml-dl, pull requests merged in 2019-10, with the labels that each got.

#23 Add links to kaggle resources
  Programming-in-Python.md
Labels: enhancement, hacktoberfest

#25 Adding AI/ML/DL/DS competition site links
  Competitions-coding-challenges.md
  Programming-in-Python.md
  README.md
  competitions.md
Labels: Hacktoberfest, enhancement

#26 Update data-generation.md
  data/data-generation.md
Labels: Hacktoberfest, enhancement

#28 Better nlp and other changes
  Programming-in-Python.md
  data/README.md
  examples/better-nlp/build/install-dependencies.sh
  examples/better-nlp/library/org/neomatrix369/better_nlp.py
  examples/better-nlp/library/org/neomatrix369/summariser_cosine.py
  examples/better-nlp/library/org/neomatrix369/summariser_nltk_sklearn.py
  examples/better-nlp/library/org/neomatrix369/summariser_pytextrank.py
  examples/better-nlp/library/org/neomatrix369/summariser_tfidf.py
  examples/better-nlp/library/org/neomatrix369/summariser_tfidf_variation.py
  examples/better-nlp/notebooks/google-colab/better_nlp_summarisers.ipynb
  examples/better-nlp/notebooks/jupyter/better_nlp_summarisers.ipynb
Labels: Hacktoberfest, enhancement

#29 Dataiku links for learning and exploration
  data/about-Dataiku.md
Labels: Hacktoberfest, enhancement

#30 Added Computer Vision topic under Julia, Python and R
  README-details.md
  README.md
Labels: Hacktoberfest, enhancement

#31 Updating zeppelin example version 2.0
  examples/apache-zeppelin/.gitignore
  examples/apache-zeppelin/Zeppelin-Dockerfile
  examples/apache-zeppelin/buildZeppelinDockerImage.sh
  examples/apache-zeppelin/installDocker.sh
  examples/apache-zeppelin/push-apache-zeppelin-docker-image-to-hub.sh
  examples/apache-zeppelin/runZeppelinDockerContainer.sh
Labels: Hacktoberfest, enhancement

#33 Update Programming-in-Python.md
  Programming-in-Python.md
Labels: Hacktoberfest, enhancement

#34 add links related to Mathematica & Wolfram Language
  README-details.md
Labels: Hacktoberfest, enhancement

#35 added wtf python repo
  Programming-in-Python.md
Labels: Hacktoberfest, enhancement

#36 Update Programming-in-Python.md
  Programming-in-Python.md
Labels: Hacktoberfest, enhancement

#37 Nlp stats probability: adding links related to these
  README-details.md
  data/README.md
  natural-language-processing/README.md
Labels: Hacktoberfest, enhancement

#38 Refactor readme & readme details into components
  ML-on-code-programming-source-code.md
  Programming-in-Python.md
  README-details.md
  README.md
  cheatsheets.md
  competitions.md
  data/README.md
  data/statistics.md
  java-jvm.md
  julia-python-and-r.md
  maths-stats-probability.md
  notebooks.md
  visualisation.md
Labels: Hacktoberfest, enhancement

#39 refactor-readme-details-into-components - second pass, fixing broken links
  README.md
  julia-python-and-r.md
  maths-stats-probability.md
Labels: Hacktoberfest, bug

#40 Update competitions.md
  competitions.md
Labels: Hacktoberfest, enhancement

#41 Added Numerai
  competitions.md
Labels: Hacktoberfest, enhancement

#43 Adding valohai example
  README-details.md
  README.md
  examples/cloud-devops-infra/valohai/nlp-cuda/README.md
  natural-language-processing/README.md
Labels: Hacktoberfest, enhancement

#42 Added Swift for TensorFlow
  README.md
Labels: Hacktoberfest, enhancement

#44 Added new active competitions
  competitions.md
Labels: Hacktoberfest, enhancement
