Repository neomatrix369/awesome-ai-ml-dl, pull requests merged in 2020-10, with the labels that each got.

#88 added code-mixing.md #hacktoberfest
  natural-language-processing/code-mixing.md
  natural-language-processing/summarise-text.md
Labels: Hacktoberfest, enhancement

#89 added measures.md #hacktoberfest
  details/dmm.md
  natural-language-processing/formulae/DMM_formula.png
  natural-language-processing/formulae/cu_metric.png
  natural-language-processing/formulae/dmm_graphical_view.png
  natural-language-processing/formulae/i_index.png
  natural-language-processing/formulae/lang_entropy.png
  natural-language-processing/formulae/likehood_DMM.png
  natural-language-processing/formulae/m_index.png
  natural-language-processing/measures.md
  natural-language-processing/ner.md
  natural-language-processing/summarise-text.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#90 added ner.md #hacktoberfest
  natural-language-processing/course-tutorial-learning-resources.md
  natural-language-processing/formulae/scoring.png
  natural-language-processing/ner.md
Labels: enhancement, hacktoberfest

#92 Add new links different categories (over 400 links)
  Programming-in-Python.md
  Python-Performance.md
  README-details.md
  cloud-devops-infra/README.md
  competitions.md
  courses.md
  data/README.md
  data/about-H2O-Driverless-AI.md
  data/about-fast.ai.md
  data/data-exploratory-analysis.md
  data/data-generation.md
  data/data-preparation.md
  data/datasets.md
  data/feature-engineering.md
  data/feature-selection.md
  data/model-analysis-interpretation-explainability.md
  details/java-jvm.md
  details/julia-python-and-r.md
  details/julia-python-and-r/deep-learning.md
  details/julia-python-and-r/machine-learning.md
  details/julia-python-and-r/reinforcement-learning.md
  details/machine-learning-algorithms.md
  details/mathematica-wolfram-Language.md
  details/maths-stats-probability.md
  details/pytorch.md
  details/visualisation.md
  natural-language-processing/README.md
  natural-language-processing/course-tutorial-learning-resources.md
  natural-language-processing/general.md
  natural-language-processing/java-jvm.md
  natural-language-processing/library-framework-models-tools-services.md
  natural-language-processing/summarise-text.md
  things-to-know.md
  time-series_anomaly-detection/time-series.md
Labels: enhancement

#93 Added GoLang resources in field of AI
  README.md
  details/julia-python-and-r.md
Labels: enhancement, hacktoberfest
